import { useState } from 'react'
import { Bot, Plus, ShieldCheck, X } from 'lucide-react'
import type { RuntimeType } from '../../../shared/contracts'
import { errorText, useAppStore } from '../store'

export default function Agents(): import('react').JSX.Element {
  const { snapshot, notify } = useAppStore()
  const [open, setOpen] = useState(false)
  const [form, setForm] = useState({ name: '', description: '', responsibility: '', runtime: 'claude' as RuntimeType, command: '', quality: '' })
  async function create(): Promise<void> {
    try { await window.moxt.createAgent({ name: form.name, icon: form.name.slice(0, 1).toUpperCase(), description: form.description, responsibility: form.responsibility, qualityBar: form.quality.split('\n').filter(Boolean), runtime: form.runtime, command: form.command || null, argsTemplate: null, workspaceIds: [], permissions: { read: true, write: true, shell: true, git: true, network: true } }); setOpen(false); notify('success', 'Agent 已加入 Agent Pool') }
    catch (error) { notify('error', errorText(error)) }
  }
  return <section className="page"><header className="page-header"><div><h1>Agent 团队</h1><p>Agent 是长期责任角色；CLI 只是可替换的执行引擎。</p></div><button className="primary" onClick={() => setOpen(true)}><Plus/>新建 Agent</button></header><div className="agent-table"><div className="table-head"><span>Agent</span><span>责任</span><span>Runtime</span><span>权限</span><span>状态</span></div>{snapshot.agents.map(agent => <div className="table-row agent-row" key={agent.id}><span><i className="agent-avatar">{agent.icon}</i><b>{agent.name}<small>{agent.description}</small></b></span><span>{agent.responsibility}</span><span>{agent.runtime}</span><span>{agent.permissions.write ? 'Workspace RW' : 'Workspace R'}</span><span><b className={`status ${agent.status.toLowerCase()}`}>{agent.status}</b></span></div>)}</div>{open && <div className="modal-backdrop"><div className="modal"><header><div><h2>创建自定义 Agent</h2><p>先定义责任和质量标准，再选择 Runtime。</p></div><button onClick={() => setOpen(false)}><X/></button></header><div className="form-grid"><label>名称<input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })}/></label><label>Runtime<select value={form.runtime} onChange={e => setForm({ ...form, runtime: e.target.value as RuntimeType })}>{snapshot.runtimes.map(r => <option value={r.type} key={r.type}>{r.label} {r.available ? '✓' : '—'}</option>)}</select></label><label className="full">角色描述<input value={form.description} onChange={e => setForm({ ...form, description: e.target.value })}/></label><label className="full">责任边界<textarea value={form.responsibility} onChange={e => setForm({ ...form, responsibility: e.target.value })}/></label><label className="full">质量标准（每行一条）<textarea value={form.quality} onChange={e => setForm({ ...form, quality: e.target.value })}/></label><label className="full">自定义可执行路径（可选）<input value={form.command} onChange={e => setForm({ ...form, command: e.target.value })} placeholder="留空使用检测到的 Runtime 路径"/></label></div><div className="permission-note"><ShieldCheck/>默认授予 Read / Write / Shell / Git / Network；创建后可按 Workspace 收紧。</div><footer><button className="secondary" onClick={() => setOpen(false)}>取消</button><button className="primary" disabled={!form.name || !form.responsibility} onClick={() => void create()}><Bot/>创建 Agent</button></footer></div></div>}</section>
}
